name: 'Hello World Docker Action'
description: 'A simple hello world action that runs in Docker'
inputs:
  name:
    description: 'Name to greet'
    required: false
    default: 'World'
  message:
    description: 'Custom message to display'
    required: false
    default: 'Hello'
outputs:
  greeting:
    description: 'The greeting message'
    value: ${{ steps.hello.outputs.greeting }}
runs:
  using: 'docker'
  image: 'docker://alpine:latest'
  entrypoint: 'sh'
  args:
    - '-c'
    - 'MESSAGE="${INPUT_MESSAGE:-Hello}"; NAME="${INPUT_NAME:-World}"; GREETING="$MESSAGE, $NAME!"; echo "$GREETING"; echo "greeting=$GREETING" >> $GITHUB_OUTPUT'
