name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Docker image name'
        required: true
        type: string
      dockerfile-path:
        description: 'Path to Dockerfile'
        required: false
        default: './Dockerfile'
        type: string
      push:
        description: 'Push to registry'
        required: false
        default: false
        type: boolean
    secrets:
      registry-username:
        required: false
      registry-password:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to registry
      if: ${{ inputs.push && secrets.registry-username }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.registry-username }}
        password: ${{ secrets.registry-password }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile-path }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.image-name }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
